export const NOTIFICATION_TYPES = {
  DOCUMENT_CREATED: 'DOCUMENT_CREATED',
  DOCUMENT_SUBMITTED: 'DOCUMENT_SUBMITTED',
  DOCUMENT_APPROVED: 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED: 'DOCUMENT_REJECTED',
  DOCUMENT_REVISION_REQUESTED: 'DOCUMENT_REVISION_REQUESTED',
  DOCUMENT_FINALIZED: 'DOCUMENT_FINALIZED',
  VERSION_CREATED: 'VERSION_CREATED',
  VERSION_UPDATED: 'VERSION_UPDATED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  COMMENT_REPLIED: 'COMMENT_REPLIED',
  COMMENT_RESOLVED: 'COMMENT_RESOLVED',
  USER_REGISTERED: 'USER_REGISTERED',
  USER_APPROVED: 'USER_APPROVED',
  USER_REJECTED: 'USER_REJECTED',
  DEADLINE_APPROACHING: 'DEADLINE_APPROACHING',
  DEADLINE_OVERDUE: 'DEADLINE_OVERDUE',
  TASK_ASSIGNED: 'TASK_ASSIGNED'
};

export const NOTIFICATION_PRIORITIES = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

export const DIGEST_FREQUENCIES = {
  NONE: 'NONE',
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY'
};

export const NOTIFICATION_CATEGORIES = {
  DOCUMENTS: 'documents',
  COMMENTS: 'comments',
  APPROVALS: 'approvals',
  SYSTEM: 'system'
};